use crate::geometry::{PathData, Point};
use std::fmt::Write;

/// Configuration for G-code generation.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct GCodeConfig {
    pub pen_up_z: f64,
    pub pen_down_z: f64,
    pub pen_thickness: f64,
    pub feedrate_xy: f64,
    pub min_feedrate_xy: f64,
    pub feedrate_z: f64,
    pub bed_width: f64,
    pub bed_height: f64,
    pub y_axis_invert: bool,
    pub auto_home: bool,
    pub travel_feedrate: f64,
    pub const_speed: bool,
    pub min_segment_time: f64,
    pub const_speed_min_feedrate: f64,
    pub const_speed_max_feedrate: f64,
}

impl Default for GCodeConfig {
    fn default() -> Self {
        GCodeConfig::low_level_defaults()
    }
}

impl GCodeConfig {
    pub fn low_level_defaults() -> Self {
        GCodeConfig {
            pen_up_z: 5.0,
            pen_down_z: 0.0,
            pen_thickness: 0.5,
            feedrate_xy: 1000.0,
            min_feedrate_xy: 200.0,
            feedrate_z: 300.0,
            bed_width: 200.0,
            bed_height: 200.0,
            y_axis_invert: false,
            auto_home: false,
            travel_feedrate: 2000.0,
            const_speed: false,
            min_segment_time: 0.05,
            const_speed_min_feedrate: 400.0,
            const_speed_max_feedrate: 3000.0,
        }
    }
}

fn fmt_coord(v: f64) -> String {
    format!("{:.3}", v)
}

fn transform_point(p: Point, config: &GCodeConfig) -> Point {
    let y = if config.y_axis_invert { -p.y } else { p.y };
    Point::new(p.x, y)
}

/// Generate full G-code from paths.
pub fn generate_gcode(paths: &[PathData], config: &GCodeConfig) -> String {
    let mut gcode = String::new();
    writeln!(gcode, "; Pen Plotter G-code generated by plottercontroll").unwrap();
    writeln!(gcode, "; Pen up Z: {:.2}  Pen down Z: {:.2}", config.pen_up_z, config.pen_down_z).unwrap();
    writeln!(gcode, "; Feedrate XY: {:.0}  Feedrate Z: {:.0}", config.feedrate_xy, config.feedrate_z).unwrap();

    // Preamble
    writeln!(gcode, "G21 ; Set units to mm").unwrap();
    writeln!(gcode, "G90 ; Use absolute positioning").unwrap();
    if config.auto_home {
        writeln!(gcode, "G28 ; Home all axes").unwrap();
    }
    writeln!(gcode, "; Pen up to start").unwrap();
    writeln!(
        gcode,
        "G1 Z{} F{} ; Pen up",
        fmt_coord(config.pen_up_z),
        fmt_coord(config.feedrate_z)
    )
    .unwrap();

    // Travel to origin
    writeln!(
        gcode,
        "G1 X0 Y0 F{} ; Move to origin",
        fmt_coord(config.travel_feedrate)
    )
    .unwrap();

    let mut path_count = 0u32;
    for path in paths {
        if path.points.len() < 2 {
            continue;
        }

        let first = transform_point(path.points[0], config);
        let _last = transform_point(path.points[path.points.len() - 1], config);

        path_count += 1;
        writeln!(gcode, "; Path {} ({} segments)", path_count, path.points.len() - 1).unwrap();

        // Move to start with pen up
        writeln!(
            gcode,
            "G0 Z{} F{} ; Pen up before move",
            fmt_coord(config.pen_up_z),
            fmt_coord(config.feedrate_z)
        )
        .unwrap();
        writeln!(
            gcode,
            "G0 X{} Y{} F{} ; Move to start",
            fmt_coord(first.x),
            fmt_coord(first.y),
            fmt_coord(config.travel_feedrate)
        )
        .unwrap();
        writeln!(
            gcode,
            "G1 Z{} F{} ; Pen down",
            fmt_coord(config.pen_down_z),
            fmt_coord(config.feedrate_z)
        )
        .unwrap();

        // Draw the path
        let mut prev = transform_point(path.points[0], config);
        for &p in &path.points[1..] {
            let tp = transform_point(p, config);
            let seg_len = prev.distance_to(tp);
            prev = tp;
            let feed = if config.const_speed && config.min_segment_time > 0.0 && seg_len > 0.001 {
                let capped = seg_len / config.min_segment_time * 60.0;
                capped.max(config.const_speed_min_feedrate).min(config.const_speed_max_feedrate)
            } else {
                config.feedrate_xy
            };
            writeln!(
                gcode,
                "G1 X{} Y{} F{}",
                fmt_coord(tp.x),
                fmt_coord(tp.y),
                fmt_coord(feed)
            )
            .unwrap();
        }

        // If closed, draw back to first point
        if path.closed && path.points.len() > 2 {
            let last = transform_point(path.points[path.points.len() - 1], config);
            let d = first.distance_to(last);
            if d > 0.01 {
                let feed = if config.const_speed && config.min_segment_time > 0.0 && d > 0.001 {
                    let capped = d / config.min_segment_time * 60.0;
                    capped.max(config.const_speed_min_feedrate).min(config.const_speed_max_feedrate)
                } else {
                    config.feedrate_xy
                };
                writeln!(
                    gcode,
                    "G1 X{} Y{} F{}",
                    fmt_coord(first.x),
                    fmt_coord(first.y),
                    fmt_coord(feed)
                )
                .unwrap();
            }
        }
    }

    // Postamble: pen up, home
    writeln!(gcode, "; Plot complete").unwrap();
    writeln!(
        gcode,
        "G1 Z{} F{} ; Pen up",
        fmt_coord(config.pen_up_z),
        fmt_coord(config.feedrate_z)
    )
    .unwrap();
    writeln!(gcode, "G1 X0 Y0 F{} ; Return to origin", fmt_coord(config.travel_feedrate)).unwrap();
    writeln!(gcode, "M84 ; Disable steppers").unwrap();
    writeln!(gcode, "; End of G-code").unwrap();

    gcode
}

/// Export G-code to a .gcode file.
pub fn export_to_file(paths: &[PathData], config: &GCodeConfig, filepath: &str) -> anyhow::Result<()> {
    let gcode = generate_gcode(paths, config);
    std::fs::write(filepath, &gcode)?;
    log::info!("Exported G-code to {}", filepath);
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_gcode_basic() {
        let paths = vec![PathData {
            points: vec![
                Point::new(10.0, 10.0),
                Point::new(20.0, 10.0),
                Point::new(20.0, 20.0),
            ],
            closed: false,
        }];
        let mut config = GCodeConfig::default();
        config.auto_home = true;
        config.y_axis_invert = true;
        let gcode = generate_gcode(&paths, &config);
        assert!(gcode.contains("G21"));
        assert!(gcode.contains("G90"));
        assert!(gcode.contains("G28"));
        assert!(gcode.contains("G0 X10.000 Y-10.000")); // y inverted, first point is G0
        assert!(gcode.contains("G1 Z0.000")); // pen down
        assert!(gcode.contains("G1 Z5.000")); // pen up
        assert!(gcode.contains("M84"));
    }

    #[test]
    fn test_empty_paths() {
        let gcode = generate_gcode(&[], &GCodeConfig::default());
        assert!(gcode.contains("G21"));
    }
}
